version: '2'
services:
  app:
    image: node:8.12
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - .:/app
    ports:
      - ${DOCKER_APP_PORT}:3000
    working_dir: /app
    command: ['npm', 'run', 'dev']
#  redis:
#    image: redis:latest
  mongo:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    ports:
      - ${DOCKER_MONGO_PORT}:27017
volumes:
  mongodb: