openapi: 3.0.0
info:
  title: approval
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/approval/{app}':
    parameters:
      - name: app
        in: path
        required: true
        schema:
          type: string
    get:
      summary: getApprovalByApp
      tags:
        - approval
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    additionalProperties: 
                      type: object
                      additionalProperties: 
                        $ref: ./models/approval-template.v1.yaml

  '/approval/{app}/{code}':
    post:
      summary: reserveApproval
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/approval-reserve.v1.yaml
              examples: {}
      description: Reserve one approval slot
      tags:
        - approval
    parameters:
      - name: app
        in: path
        required: true
        schema:
          type: string
      - name: code
        in: path
        required: true
        schema:
          type: string
    get:
      summary: getApprovalByCode
      responses:
        '200':
          description: OK
      tags:
        - approval
  '/approval/{app}/{code}/{id}':
    get:
      summary: getApprovalById
      tags:
        - approval
      responses:
        '200':
          description: OK
    put:
      summary: updateApprovalById
      description: ''
      tags:
        - approval
      responses:
        '200':
          description: OK
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: approval id
      - name: app
        in: path
        required: true
        schema:
          type: string
      - name: code
        in: path
        required: true
        schema:
          type: string
  '/approval/{app}/{code}/{id}/approve':
    parameters:
      - name: id
        in: path
        required: true
        description: approval id
        schema:
          type: string
      - name: app
        in: path
        required: true
        schema:
          type: string
      - name: code
        in: path
        required: true
        schema:
          type: string
    post:
      summary: approveApproval
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                next:
                  type: array
                  items:
                    type: object
                    properties:
                      code:
                        type: string
                      approver:
                        type: string
                      auto_approve:
                        type: boolean
                    required:
                      - code
      tags:
        - approval
  '/approval/{app}/{code}/{id}/reject/':
    delete:
      summary: rejectApproval
      tags:
        - approval
      parameters:
        - in: path
          name: id
          required: true
          description: approval id
          schema:
            type: string
        - in: path
          name: app
          required: true
          schema:
            type: string
        - in: path
          name: code
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          
components:
  schemas: {}
